# Generated by Django 4.2.30 on 2026-08-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='Ejemplo: proteccion, domiciliario o industrial', max_length=80, unique=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Determina el orden de las categorías')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(help_text='Se completa automáticamente desde el administrador', max_length=200, unique=True)),
                ('subtitulo', models.CharField(help_text='Ejemplo: Protección eléctrica', max_length=120)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal que aparecerá en el catálogo', upload_to='productos/')),
                ('texto_alternativo', models.CharField(blank=True, help_text='Descripción accesible de la imagen', max_length=180)),
                ('etiqueta_visual', models.CharField(blank=True, help_text='Ejemplo: PROTECCIÓN, SEGURIDAD o LÍNEA DLX', max_length=80)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Determina la posición del producto en el catálogo')),
                ('publicado', models.BooleanField(default=True, help_text='Desactívalo para ocultar el producto del catálogo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=180)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Determina el orden de la característica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Característica del producto',
                'verbose_name_plural': 'Características de los productos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
