# Generated by Django 4.2.30 on 2026-08-24 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_alter_cotizacion_servicio_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Déjalo vacío para una familia principal. Selecciona una familia para crear una subcategoría.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(help_text='Ejemplo: electricidad o interruptores-automaticos', max_length=80, unique=True),
        ),
    ]
