# Generated by Django 4.2.30 on 2026-08-24 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_padre_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Clasificación de producto', 'verbose_name_plural': 'Clasificaciones de productos'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, help_text='Desactive esta opción para ocultar la clasificación sin eliminarla.', verbose_name='Visible en el catálogo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Los valores menores aparecen primero. Ejemplo: 1, 2, 3.', verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Deje este campo sin seleccionar para registrar una familia principal. Para crear una subcategoría, seleccione la familia a la que pertenece.', limit_choices_to={'padre__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='core.categoria', verbose_name='Familia principal'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(help_text='Texto único utilizado en la dirección web. Se genera automáticamente desde el nombre. Ejemplo: interruptores-automaticos.', max_length=80, unique=True, verbose_name='Identificador web'),
        ),
    ]
