# Generated by Django 4.2.30 on 2026-08-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_options_alter_categoria_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único utilizado para identificar el producto. Puede dejarse vacío.', max_length=80, null=True, unique=True, verbose_name='Código interno o SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Lexo', max_length=80, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo oficial indicado por el fabricante. Puede dejarse vacío si todavía no está disponible.', max_length=100, verbose_name='Modelo o referencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(help_text='Seleccione la subcategoría específica del producto.', limit_choices_to={'activa': True, 'padre__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.categoria', verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Active esta opción cuando el producto esté listo para aparecer públicamente.', verbose_name='Publicado en el catálogo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(help_text='Se genera automáticamente desde el nombre del producto.', max_length=200, unique=True, verbose_name='Identificador web'),
        ),
        migrations.CreateModel(
            name='EspecificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Corriente nominal, Polos o Protección IP.', max_length=100, verbose_name='Nombre de la especificación')),
                ('valor', models.CharField(help_text='Ejemplo: 16, 1P+N o IP44.', max_length=100, verbose_name='Valor')),
                ('unidad', models.CharField(blank=True, help_text='Ejemplo: A, V, mm o Hz.', max_length=30, verbose_name='Unidad')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='core.producto')),
            ],
            options={
                'verbose_name': 'Especificación técnica',
                'verbose_name_plural': 'Especificaciones técnicas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='especificacionproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='especificacion_unica_por_producto'),
        ),
    ]
