# Generated by Django 4.2.30 on 2026-08-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_codigo_producto_marca_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', help_text='Déjalo vacío si la marca todavía no está confirmada', max_length=80, verbose_name='Marca'),
        ),
    ]
