# Generated by Django 4.2.30 on 2026-09-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Identificador web')),
                ('logo', models.ImageField(blank=True, upload_to='marcas/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Marca anterior'),
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: 2 polos · 25 A', max_length=140, verbose_name='Nombre de la variante')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo o referencia')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código o SKU')),
                ('imagen', models.ImageField(blank=True, upload_to='productos/variantes/')),
                ('disponible', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='core.producto')),
            ],
            options={
                'verbose_name': 'Variante del producto',
                'verbose_name_plural': 'Variantes de los productos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=120)),
                ('unidad', models.CharField(blank=True, help_text='Ejemplo: A, W, mm, V o mA', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='core.varianteproducto')),
            ],
            options={
                'verbose_name': 'Especificación de variante',
                'verbose_name_plural': 'Especificaciones de las variantes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='marca_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='core.marca', verbose_name='Marca'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='variante_unica_por_producto'),
        ),
    ]
