# Generated by Django 4.2.30 on 2026-09-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_marca_alter_producto_marca_varianteproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.producto', verbose_name='Producto solicitado'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='core.varianteproducto', verbose_name='Variante solicitada'),
        ),
        migrations.AddConstraint(
            model_name='especificacionvariante',
            constraint=models.UniqueConstraint(fields=('variante', 'nombre'), name='especificacion_unica_por_variante'),
        ),
    ]
