# Generated by Django 4.2.30 on 2026-09-16 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cotizacion_producto_cotizacion_variante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador estable utilizado por las cargas automáticas para actualizar la imagen sin duplicarla.', max_length=220, unique=True, verbose_name='Identificador de importación')),
                ('imagen', models.ImageField(upload_to='productos/catalogo/')),
                ('texto_alternativo', models.CharField(blank=True, max_length=180)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_catalogo', to='core.producto')),
                ('variantes', models.ManyToManyField(blank=True, help_text='Variantes o códigos representados por esta fotografía. Puede seleccionar varias cuando comparten la misma imagen.', related_name='imagenes_catalogo', to='core.varianteproducto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
