# Generated by Django 4.2.30 on 2026-09-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_imagenes_catalogo_relacionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('slug', models.SlugField(help_text='Se genera automáticamente desde el nombre del proyecto.', max_length=200, unique=True, verbose_name='Identificador web')),
                ('sector', models.CharField(choices=[('residencial', 'Residencial'), ('hospitalario', 'Salud'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('infraestructura', 'Infraestructura')], max_length=30)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal que aparecerá en la sección de proyectos.', upload_to='proyectos/')),
                ('texto_alternativo', models.CharField(blank=True, help_text='Descripción accesible de la imagen.', max_length=180)),
                ('constructora', models.CharField(blank=True, max_length=180)),
                ('mandante', models.CharField(blank=True, max_length=180, verbose_name='Cliente o mandante')),
                ('estado', models.CharField(choices=[('en_construccion', 'En construcción'), ('finalizado', 'Finalizado'), ('en_ejecucion', 'En ejecución'), ('planificado', 'Planificado')], max_length=30)),
                ('periodo', models.CharField(blank=True, help_text='Ejemplo: Abril 2021 – mayo 2023.', max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('url_mapa', models.URLField(blank=True, help_text='Opcional. Si se deja vacío, se generará una búsqueda en Google Maps usando la dirección registrada.', max_length=500, verbose_name='URL de Google Maps')),
                ('url_referencia', models.URLField(blank=True, help_text='Sitio oficial del proyecto o del mandante.', max_length=500, verbose_name='URL de referencia')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado en el sitio')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-destacado', 'nombre'],
            },
        ),
    ]
